version: '3'
services:
    elasticsearch:
        image: elasticsearch:5.2.0
        networks:
            - logging
        environment:
            LOGSPOUT: ignore
    logstash:
        image: logstash:5.2.0
        command: logstash -e 'input { tcp { port => 5000 codec => json } udp { port => 5000 codec => json } } output { elasticsearch { hosts => "elasticsearch:9200" }}'
        networks:
            - logging
        depends_on:
            - elasticsearch
        environment:
            LOGSPOUT: ignore
    logspout:
        image: conoreby/logstash-logspout
        networks:
            - logging
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        deploy:
            mode: global
        depends_on:
            - logstash
        environment:
            LOGSPOUT: ignore
            ROUTE_URIS: logstash+tcp://logstash:5000
    kibana:
        image: kibana:5.2.0
        ports:
            - "5601:5601"
        environment:
            ELASTICSEARCH_URL: http://elasticsearch:9200
            LOGSPOUT: ignore
        networks:
            - logging
        depends_on:
            - elasticsearch

networks:
    logging:
        driver: overlay
